name: "GCClientFramework"
author: Khinenw
version: 0.0.1 alpha
description: "An minigame framework for GameCore."
main: gamecore\gcframework\GCClientFramework
api: 1.12.0
depend: [GameCoreFramework]